# .github/FUNDING.yml
# This file configures the "Sponsor" button on your GitHub repository.

# Enable GitHub Sponsors for your username
github: [razalazar]

# Custom donation platforms
custom: ['https://www.buymeacoffee.com/asalazar']
